version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home

  swagger:
    image: swaggerapi/swagger-editor
    container_name: swagger
    restart: always
    ports:
      - "8088:8080"

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - influxdb_home:/var/lib/influxdb

  rethinkdb:
    image: rethinkdb
    container_name: rethinkdb
    restart: always
    ports:
      - "8089:8080"
      - "28015:28015"
    volumes:
      - rethinkdb_home:/data

volumes:
  dbdata:
  jenkins_home:
  influxdb_home:
  rethinkdb_home:
