apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: jenkins_home
      mountPath: /var/jenkins_home
  volumes:
  - name: jenkins_home
    emptyDir: {}